# Lab 03: Fun with `pandas`!

Below are some exercises to get you working with `pandas` to manipulate data. As always, get as far as you can, and ask for help when you need it! Your teacher (me), you instructor, and your classmates are all here to help each other get better at coding. Getting the code to work is important, but do also take the time to make sure you understand what the commands are doing. This time, (with the exception of the Stroop challenge), all I've given you is the code to download the data. Then you are on your own. For the Stroop challenge, I gave the you code for the first step—after that, it's up to you :-)

## Music sales challenge

Write a script that:

1. Combines the tables of best-selling physical singles and best-selling digital singles on the Wikipedia page "List_of_best-selling_singles"
2. Adds a column which marks whether each row is from the list of physical singles or digital singles
3. Outputs the artist and single name for the year you were born. If there is no entry for that year, take the closest year after you were born.
4. Outputs the artist and single name for the year you were 15 years old.

In [1]:
# Starter code...

#%pip install lxml
import pandas as pd

rawdata = pd.read_html("https://en.wikipedia.org/wiki/List_of_best-selling_singles")

In [2]:
# 1.

# getting the correct dataframes
physical_df = rawdata[0]
digital_df = rawdata[3]

# merging the dataframes
merged_df = pd.concat([physical_df, digital_df])

# fixing the misaligned indexes
merged_df = merged_df.reset_index(drop=True)

# lets check the df
merged_df

,Artist,Single,Released,Sales (in millions),Source
0,Bing Crosby,"""White Christmas""",1942,50,[1]
1,Elton John,"""Something About the Way You Look Tonight""/""Ca...",1997,33,[1]
2,Bing Crosby,"""Silent Night""",1935,30,[2]
3,Tino Rossi,"""Petit Papa Noël""",1946,30,[3]
4,Bill Haley & His Comets,"""Rock Around the Clock""",1954,25,[4][5]
5,Whitney Houston,"""I Will Always Love You""",1992,24,[6]
6,Elvis Presley,"""It's Now or Never""",1960,20,[7][8]
7,USA for Africa,"""We Are the World""",1985,20,[9]
8,The Ink Spots,"""If I Didn't Care""",1939,19[disputed – discuss],[10]
9,Celine Dion,"""My Heart Will Go On""",1997,18,[11]
10,Mariah Carey,"""All I Want For Christmas Is You""",1994,16,[12]
11,Baccara,"""Yes Sir, I Can Boogie""",1977,16,[13]
12,Bryan Adams,"""(Everything I Do) I Do It for You""",1991,15,[14]
13,John Travolta and Olivia Newton-John,"""You're the One That I Want""",1978,15,[15]
14,Ed Sheeran,"""Shape of You""",2017,41.5[a],[46][47]
15,Luis Fonsi featuring Daddy Yankee,"""Despacito""",2017,36.1[a],[46][47]
16,Rihanna featuring Drake,"""Work""",2016,32.5[a],[48]
17,The Chainsmokers and Coldplay,"""Something Just Like This""",2017,21.5[a],[46][47]
18,Ed Sheeran,"""Perfect""",2017,21.4[a],[46][47]
19,Wiz Khalifa featuring Charlie Puth,"""See You Again""",2015,20.9[a],[49]
20,The Chainsmokers featuring Halsey,"""Closer""",2016,20.7[a],[50][46]
21,Adele,"""Rolling in the Deep""",2011,20.6,[51][52][53]
22,Mark Ronson featuring Bruno Mars,"""Uptown Funk""",2015,20[a],[49]
23,Billie Eilish,"""Bad Guy""",2019,19.5[a],[54]
24,Ed Sheeran,"""Thinking Out Loud""",2015,19.5[a],[49]
25,Camila Cabello featuring Young Thug,"""Havana""",2017,19.0[a],[46][47]
26,Lil Nas X,"""Old Town Road""",2018,18.4[a],[54]
27,Carly Rae Jepsen,"""Call Me Maybe""",2011,18.0,[55]
28,Taylor Swift,"""Love Story""",2008,18.0[a],[56]
29,Adele,"""Someone Like You""",2011,17.0,[57]
30,Rihanna,"""Needed Me""",2016,17.0[a],[48]
31,Shawn Mendes and Camila Cabello,"""Señorita""",2019,16.1[a],[54]
32,Imagine Dragons,"""Radioactive""",2012,16[a],[58]
33,Imagine Dragons,"""Believer""",2017,15.4[a],[59][60]
34,Drake,"""God's Plan""",2018,15.3[a],[47]

In [3]:
# 2.

# we find the index we wanna call physical
index = merged_df.index[0:14]

# digital is the default
merged_df['type'] = 'digital'

# we change the type to physical in the given index
merged_df.loc[index, 'type'] = 'physical'

# lets check
merged_df

,Artist,Single,Released,Sales (in millions),Source,type
0,Bing Crosby,"""White Christmas""",1942,50,[1],physical
1,Elton John,"""Something About the Way You Look Tonight""/""Ca...",1997,33,[1],physical
2,Bing Crosby,"""Silent Night""",1935,30,[2],physical
3,Tino Rossi,"""Petit Papa Noël""",1946,30,[3],physical
4,Bill Haley & His Comets,"""Rock Around the Clock""",1954,25,[4][5],physical
5,Whitney Houston,"""I Will Always Love You""",1992,24,[6],physical
6,Elvis Presley,"""It's Now or Never""",1960,20,[7][8],physical
7,USA for Africa,"""We Are the World""",1985,20,[9],physical
8,The Ink Spots,"""If I Didn't Care""",1939,19[disputed – discuss],[10],physical
9,Celine Dion,"""My Heart Will Go On""",1997,18,[11],physical
10,Mariah Carey,"""All I Want For Christmas Is You""",1994,16,[12],physical
11,Baccara,"""Yes Sir, I Can Boogie""",1977,16,[13],physical
12,Bryan Adams,"""(Everything I Do) I Do It for You""",1991,15,[14],physical
13,John Travolta and Olivia Newton-John,"""You're the One That I Want""",1978,15,[15],physical
14,Ed Sheeran,"""Shape of You""",2017,41.5[a],[46][47],digital
15,Luis Fonsi featuring Daddy Yankee,"""Despacito""",2017,36.1[a],[46][47],digital
16,Rihanna featuring Drake,"""Work""",2016,32.5[a],[48],digital
17,The Chainsmokers and Coldplay,"""Something Just Like This""",2017,21.5[a],[46][47],digital
18,Ed Sheeran,"""Perfect""",2017,21.4[a],[46][47],digital
19,Wiz Khalifa featuring Charlie Puth,"""See You Again""",2015,20.9[a],[49],digital
20,The Chainsmokers featuring Halsey,"""Closer""",2016,20.7[a],[50][46],digital
21,Adele,"""Rolling in the Deep""",2011,20.6,[51][52][53],digital
22,Mark Ronson featuring Bruno Mars,"""Uptown Funk""",2015,20[a],[49],digital
23,Billie Eilish,"""Bad Guy""",2019,19.5[a],[54],digital
24,Ed Sheeran,"""Thinking Out Loud""",2015,19.5[a],[49],digital
25,Camila Cabello featuring Young Thug,"""Havana""",2017,19.0[a],[46][47],digital
26,Lil Nas X,"""Old Town Road""",2018,18.4[a],[54],digital
27,Carly Rae Jepsen,"""Call Me Maybe""",2011,18.0,[55],digital
28,Taylor Swift,"""Love Story""",2008,18.0[a],[56],digital
29,Adele,"""Someone Like You""",2011,17.0,[57],digital
30,Rihanna,"""Needed Me""",2016,17.0[a],[48],digital
31,Shawn Mendes and Camila Cabello,"""Señorita""",2019,16.1[a],[54],digital
32,Imagine Dragons,"""Radioactive""",2012,16[a],[58],digital
33,Imagine Dragons,"""Believer""",2017,15.4[a],[59][60],digital
34,Drake,"""God's Plan""",2018,15.3[a],[47],digital

In [6]:
3. 
merged_df[merged_df['Released'] == 1997][['Artist', 'Single', 'Released']]

# there is no 2002 :=(

        Artist                                             Single  Released
1   Elton John  "Something About the Way You Look Tonight"/"Ca...      1997
9  Celine Dion                              "My Heart Will Go On"      1997

In [7]:
4. 
merged_df[merged_df['Released'] == 2017][['Artist', 'Single', 'Released']]

                                 Artist                      Single  Released
14                           Ed Sheeran              "Shape of You"      2017
15    Luis Fonsi featuring Daddy Yankee                 "Despacito"      2017
17        The Chainsmokers and Coldplay  "Something Just Like This"      2017
18                           Ed Sheeran                   "Perfect"      2017
25  Camila Cabello featuring Young Thug                    "Havana"      2017
33                      Imagine Dragons                  "Believer"      2017

3## Space challenge

1. Make a single dataframe that combines the space missions from the 1950's to the 2020's
2. Write a script that returns the year with the most launches
3. Write a script that returns the most common month for launches
4. Write a script that ranks the months from most launches to fewest launches

In [30]:
# Starter code...

#%pip install lxml
import pandas as pd

rawdata = pd.read_html("https://en.wikipedia.org/wiki/Timeline_of_Solar_System_exploration")

In [64]:
# 1. Make a single dataframe that combines the space missions from the 1950's to the 2020's

# merging the dataframes
merged_df_space = pd.concat([rawdata[0],rawdata[7]])
merged_df_space

# fixing the misaligned indexes
merged_df_space = merged_df_space.reset_index(drop=True)

In [65]:
# 2. Write a script that returns the year with the most launches

# Converting to datetime format
merged_df_space['Launch date'] = pd.to_datetime(merged_df_space['Launch date'], format='%d %B %Y')

# Extract the year from the 'Launch date' column
merged_df_space['Year'] = merged_df_space['Launch date'].dt.year

# Count the occurrences of each year
year_counts = merged_df_space['Year'].value_counts()

# Find the year with the most launches
most_launches_year = year_counts.idxmax()
most_launches_count = year_counts.max()

# Print the result
print(f"The year with the most launches is {most_launches_year} with {most_launches_count} launches.")

The year with the most launches is 2023 with 6 launches.

In [66]:
# 3. Write a script that returns the most common month for launches

# Converting to datetime format
merged_df_space['Launch date'] = pd.to_datetime(merged_df_space['Launch date'], format='%d %B %Y')

# Extract the year from the 'Launch date' column
merged_df_space['Month'] = merged_df_space['Launch date'].dt.month

# Count the occurrences of each month
month_counts = merged_df_space['Month'].value_counts()

# Find the year with the most launches
most_launches_month = month_counts.idxmax()
most_launches_count = month_counts.max()

#Print the result
print(f"The month with the most launches is {most_launches_month} with {most_launches_count} launches.")

# so it is october, because it is the tenth month :=)

The month with the most launches is 10 with 4 launches.

In [71]:
# 4. Write a script that ranks the months from most launches to fewest launches
month_counts.sort_values(ascending = False)

# october, november, march and july had the most launches

Month
10    4
11    4
3     4
7     4
2     3
9     3
1     2
12    2
8     2
6     1
4     1
5     1
Name: count, dtype: int64

## Supervillain challenge

1. Write a script that combines the tables showing supervillain debuts from the 30's through the 2010's
2. Write a script that ranks each decade in terms of how many supervillains debuted in that decade
3. Write a script that ranks the different comics companies in terms of how many supervillains they have, and display the results in a nice table (pandas dataframe)

In [77]:
rawdata = pd.read_html("https://en.wikipedia.org/wiki/List_of_comic_book_supervillain_debuts")

In [78]:
# merging dataframes
rawdata[0]

    0                                                  1
0 NaN  This article has multiple issues. Please help ...
1 NaN  This article includes a list of general refere...
2 NaN  This article needs additional citations for ve...

## Stroop challenge

Every year between 2015 and 2021, the students in my Language, Cognition, and the Brain course participated in a version of the Stroop task. Using a stopwatch (ok, using their phones), they recorded how fast they could say a list of things (either reading or naming colors or color words). The column names mean "Reading with No Interference", "Naming with Interference", "Naming with No Interference", and "Reading with Interference". The times are in seconds.

### Stroop challenge 1: 
Transform these data from wide format to long format, so that the result is a dataframe with
- 1 column named "Participant_id" with a unique number for each participant (you can use the row indices)
- 1 column named "Year" with the year data
- 1 column named "Task" that shows which task they were doing
- 1 column named "RT" that shows their response time

In [79]:
# Starter code 1...

df = pd.read_csv("https://raw.githubusercontent.com/ethanweed/Stroop/master/Stroop-raw-over-the-years.csv")
df.head()

   Reading_NoInt  Naming_Int  Naming_NoInt  Reading_Int  Year
0           4.16        6.76          4.45         4.65  2015
1           4.35        7.73          4.78         4.46  2015
2           3.60        7.00          4.00         3.50  2015
3           3.90        9.03          4.60         6.30  2015
4           4.22        9.98          6.83         6.24  2015

In [ ]:
# Starter code 2...

# Make a new column using the dataframe indices as particpant numbers

df.index.name = 'Participant_id'
df = df.reset_index()

#df.reset_index(inplace = True)
# NOTE: This line does exactly the same thing as the line above:
# it replaces the original df with a new df with the updated index. That's what
# "inplace = True" means. Or, you can just assign the dataframe with the updated index
# to a new dataframe with the same name as the old dataframe, which is what I did above.
# The end result is the same.

df

## Stroop challenge 2 (Advanced!!!):

Make a new dataframe which shows the mean response time (in seconds) for each task for each year.